spring:
  application:
    name: boot-chat
  ai:
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          #username: "root"
          #password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: "gemma:2b"
