app:
  db:
    url: jdbc:p6spy:mysql://10.16.25.49:3306/boot_chat?characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: "BAPaS#c5Xm5J"
spring:
  datasource:
    hikari:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: ${app.db.url}
      username: ${app.db.username}
      password: ${app.db.password}
      connection-test-query: select 1
      maximum-pool-size: 50
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: ${app.db.url}
    username: ${app.db.username}
    password: ${app.db.password}
  jpa:
    hibernate:
    #ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true

  data:
    redis:
      host: 10.16.24.54
      port: 30000
      password:
  application:
    name: boot-chat
  webflux:
    base-path: /chat-be
  minio:
    endpoint: https://minio-oss.yonyougov.top
    accessKey: mpBzSRtOuNoIA9PP
    secretKey: 6DCki2PzfXuAq7DGYw9gzWzhJj0eV0xm
    bucketName: chat
  ai:
    vectorstore:
      milvus:
        client:
          host: 10.16.26.105
          port: 19530
          #username: "root"
          #password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: "gemma:2b"
    qianfan:
      chat:
        base-url: https://aip.baidubce.com/rpc/2.0/ai_custom
        options:
          model: yi_34b_chat
          temperature: 0.7
        enabled: true
      api-key: RwZuiUNK5VsBRFfGLHnJVXyN
      secret-key: ZEY3hRCBi5VL6JibQEp6KNcg7yR8iODC
    zhipuai:
      api-key: 9660fddee18fded9bc303ab57d53c5a6.mdgfeOaeBoP1Raot
      image:
        enabled: true
        options:
          model: "cogview-3"
        api-key: 9660fddee18fded9bc303ab57d53c5a6.mdgfeOaeBoP1Raot
  main:
    allow-bean-definition-overriding: true
#logging:
#  level:
#    root: info
yondif:
  file:
    path: "E://data/wiki"
  jwt:
    secret-key: "yNbJvsFhHF+Coih+GBCiqnvb2eZADBeOUeZQF7joKpk="
  cors:
    allowed-origins:
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://localhost:58698
  proxy:
    enable: true
    ip: 10.16.22.246
    port: 8889
    domains:
      - aip.baidubce.com
server:
  servlet:
    context-path: /${spring.application.name}
#  port: 8080
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG