spring:
  application:
    name: boot-chat
  webflux:
    base-path: /chat-be
  ai:
    vectorstore:
      milvus:
        client:
          host: 10.16.26.105
          port: 19530
          #username: "root"
          #password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: "gemma:2b"
    qianfan:
      chat:
        base-url: https://aip.baidubce.com/rpc/2.0/ai_custom
        options:
          model: yi_34b_chat
          temperature: 0.7
        enabled: true
      api-key: RwZuiUNK5VsBRFfGLHnJVXyN
      secret-key: ZEY3hRCBi5VL6JibQEp6KNcg7yR8iODC
logging:
  level:
    root: debug
yondif:
  proxy:
    enable: true
    ip: 10.16.22.246
    port: 8889
    domains:
      - aip.baidubce.com